### ISSUE TITLE
transactions not showinfgup correctly

### ISSUE THREAD

**Issue by dariquewarren** [CoopersHill/finance-SPA#4]
AFTER USING THE POST TRANSACTION FROM NEW TRANSACTIONS ARE SELECTIVELY SHOWING UP.
SOMETIMES THEY SHOW SOMETIMES THEY DONT SHOW UP.

LOOK INTO CORS ISSUE. PERMANENT FIX NEEDED. LOOK AT CORSANYWHERE

FETCH CALL SEEMS TO BE DELAYED BY ALOOOOOT

**Comment by hawarren** [comment]
Also, posting transactions does not appear to work. Since Week 1 feature release is to display transactions, we should remove the create transaction button and just feed transactions into the API to be retrieved by the frontend.
@hawarren (Hanif) will add some dummy transactions to the api to be displayed.

We will try to address loading performance and updating transactions in future releases.
